[workspace]
resolver = "2"
members = ["crates/kongzilla-beacon", "crates/kongzilla-core", "crates/kongzilla-wasm"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/matyushinleonid/kongzilla"
rust-version = "1.82"

[workspace.dependencies]
kongzilla-core = { path = "crates/kongzilla-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
