//! Regenerates `src/ranking_table.rs`.
//!
//! Prints a hand-strength ordering computed as all-in equity against a uniformly
//! random hand, estimated by Monte Carlo with a fixed seed. Run it with
//! `make ranking`; the output is committed so the slider is deterministic and
//! costs nothing at runtime.

use kongzilla_core::cards::{Card, CardSet, Combo, HandClass, NUM_CARDS};
use kongzilla_core::eval::eval;

const SAMPLES: u32 = 400_000;

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }

    fn below(&mut self, bound: u32) -> u32 {
        (self.next() % u64::from(bound)) as u32
    }
}

fn representative(class: HandClass) -> Combo {
    class.combos().next().expect("every class has combos")
}

fn equity_vs_random(hero: Combo, rng: &mut Rng) -> f64 {
    let hero_mask = hero.mask();
    let mut total = 0.0;
    for _ in 0..SAMPLES {
        let mut used = hero_mask;
        let mut drawn = [Card::from_index(0); 7];
        let mut count = 0;
        while count < 7 {
            let card = Card::from_index(rng.below(NUM_CARDS as u32) as u8);
            if used.contains(card) {
                continue;
            }
            used.insert(card);
            drawn[count] = card;
            count += 1;
        }
        let board: CardSet = drawn[2..7].iter().copied().collect();
        let villain: CardSet = drawn[0..2].iter().copied().collect();
        let hero_rank = eval(board.union(hero_mask));
        let villain_rank = eval(board.union(villain));
        total += match hero_rank.cmp(&villain_rank) {
            std::cmp::Ordering::Greater => 1.0,
            std::cmp::Ordering::Equal => 0.5,
            std::cmp::Ordering::Less => 0.0,
        };
    }
    total / f64::from(SAMPLES)
}

fn main() {
    let mut scored: Vec<(HandClass, f64)> = HandClass::all()
        .map(|class| {
            let seed =
                0x9E37_79B9_7F4A_7C15u64 ^ u64::from(class.index()).wrapping_mul(0x2545_F491);
            let mut rng = Rng(seed);
            (class, equity_vs_random(representative(class), &mut rng))
        })
        .collect();
    scored.sort_by(|a, b| b.1.partial_cmp(&a.1).expect("no NaN equities"));

    println!("//! Generated by `make ranking` - do not edit by hand.");
    println!("//!");
    println!("//! Hand classes ordered by all-in equity against a uniformly random hand,");
    println!("//! estimated with {SAMPLES} Monte Carlo samples per class and a fixed seed.");
    println!();
    println!("use crate::cards::{{HandClass, NUM_CLASSES}};");
    println!();
    println!("/// Strongest first.");
    println!("pub(crate) const EQUITY_VS_RANDOM: [HandClass; NUM_CLASSES] = [");
    for chunk in scored.chunks(6) {
        let line: Vec<String> = chunk
            .iter()
            .map(|(class, _)| format!("HandClass::from_index({})", class.index()))
            .collect();
        println!("    {},", line.join(", "));
    }
    println!("];");
}
